version: '3.8'

services:
  db:
    build: .
    container_name: mysql_web
    environment:
      MYSQL_DATABASE: mysql_web
      MYSQL_USER: web
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
